spring.application.name=ec2java
#Database config
spring.datasource.username=admin
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://musicdb.cyja4w886n92.us-east-1.rds.amazonaws.com:3306/musicdb
#spring.datasource.url=jdbc:mysql://localhost:3306/musicbd?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.jpa.show-sql=true

#Request size config
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

#S3 bucket an user access config
cloud.aws.region.static=us-east-1
cloud.aws.s3.bucket.name=amzn-s3-music-bucket

