name: Compilar y Subir a S3
on:
  push:
    branches:
      - main 

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el codigo
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        java-version: '21' 
        distribution: 'temurin'
        cache: 'maven' 

    - name: Compilar el proyecto (Maven)
      run: mvn clean package -DskipTests

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Subir el .jar a S3
      run: |
        JAR_PATH=$(find target/ -name "*.jar" | grep -v "plain.jar" | head -n 1)
        echo "Subiendo $JAR_PATH a S3..."
        
        aws s3 cp $JAR_PATH s3://${{vars.S3_BUCKET_NAME}}/app-latest.jar